---
title: "Iteration and Lisr Cols"
author: "Jessica Flynn"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
set.seed(1)
```

## Lists

You can put anything in a list

```{r}
l = list(vec_numeric = 5:8,
vec_char = c("My", "name", "is", "Jeff"),
vec_logical = c(TRUE, TRUE,FALSE, TRUE, FALSE, FALSE),
mat = matrix(1:8, nrow = 2, ncol = 4),
summary = summary(rnorm(100))
)
```

```{r}
l$vec_numeric
l[[1]]
l[[1]][1:3]
```

## for loops

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)

```

Pause and get my old function
```{r}

```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

Apply function
```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop: 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```


Let's try map: 

```{r}
output = map(list_norms, mean_and_sd)
output = map(list_norms, median)
output = map(list_norms, IQR)

```


```{r}
output = map(.x = list_norms, ~ mean_and_sd(.x))
```

## Map variants

```{r}
output = map_dbl(list_norms, median, .id = "input")
output = map_df(list_norms, mean_and_sd, .id = "input")
```


```{r}
```

## List columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df %>% pull(name)
listcol_df %>% pull(samp)

listcol_df$samp[[1]]
listcol_df %>% 
  filter(name == "a")

```

Let's try some operations..

```{r}
mean_and_sd(listcol_df$samp[[1]])
```

```{r}
map(listcol_df$samp, mean_and_sd)
```

So... can I add a list column? Yes.

```{r}
listcol_df = 
  listcol_df %>% 
  mutate(summary = map(samp, mean_and_sd), 
         medians = map_dbl(samp, median))

listcol_df
```

## Nested data 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Get our list columns

```{r}
weather_nest = 
  weather_df %>% 
  nest(data = date:tmin)

weather_nest

weather_nest %>% pull(name)
weather_nest %>% pull(data)
```

Suppose I want to regress `tmax` on `tmin` for each station

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(weather_nest$data[[1]])
```

We can also map this

```{r}
map(weather_nest$data, weather_lm)

map(weather_nest$data, ~lm(tmax ~ tmin, data = .x)) ## less preferred- better to write function
```

What about a map in a list column

```{r}
weather_nest = 
  weather_nest %>% 
  mutate(models = map(data, weather_lm))

weather_nest
```

