---
title: "Writing Funciton"
author: "Jessica Flynn"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

```{r}
set.seed(1)
```

## Do something simple

```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```


I want a function to compute z scores

```{r}
z_scores = function(x){
  
  if (!is.numeric(x)) {
    stop("Argument x must be numeric")
  } else if (length(x) < 3) {
    stop("Input must have at least 3 numbers")
  }
  
   z = (x - mean(x)) / sd(x)
   return(z)
  
}

z_scores(x_vec)

```


Try my function on some other things. These should give errors

```{r, error = TRUE}
z_scores(3)
z_scores("my name is jeff")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## Multiple Outputs

```{r}
mean_and_sd = function(x){
  
  if (!is.numeric(x)) {
    stop("Argument x must be numeric")
  } else if (length(x) < 3) {
    stop("Input must have at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(mean = mean_x, 
       sd = sd_x)
}
```

Check that the function works

```{r}
mean_and_sd(x_vec)
```

## Multiple Inputs


I'd like to do this with a function
```{r}
sim_data = tibble(
  x = rnorm(100, mean = 4, sd = 3)
)

sim_data %>% 
  summarize(
    mu_hat = mean(x),
    sigma_hat = sd(x)
  )
```

Write function
```{r}
sim_mean_sd = function(n, mu, sigma) {
  
  sim_data = tibble(
    x = rnorm(n = n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}


sim_mean_sd(n = 100,mu = 3,sigma = 6)
```

